name: Upload a Test Coverage Report

inputs:
  filename:
    required: true
    type: string
  scheme_name:
    required: true
    type: string
  token:
    description: 'A CodeCov Token'
    required: true

runs:
  using: "composite"

  steps:
    - name: Install dependencies
      run: |
        brew tap a7ex/homebrew-formulae
        brew install xcresultparser
      shell: bash

    - name: Convert the test report
      run: |
        xcresultparser -o cobertura "test_output/${{ inputs.filename }}.xcresult" > cobertura.xml
      shell: bash
  
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5.5.1
      with:
        token: ${{ inputs.token }}
        flags: ${{ inputs.scheme_name }}
        fail_ci_if_error: true
        verbose: true
        files: ./cobertura.xml

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.filename }}
        path: test_output
