#!/bin/bash
#MISE description="Lint the flare package using SwiftLint and SwiftFormat"
#MISE usage flag "-f --fix" help="Fix the fixable issues"

set -eo pipefail

if [ "$usage_fix" = "true" ]; then
  swiftformat Sources Tests
  swiftlint lint --fix --strict --config .swiftlint.yml Sources Tests
else
  swiftformat Sources Tests --lint
  swiftlint lint --strict --config .swiftlint.yml Sources Tests
fi